name: Docker Image Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install buildx
        run: |
          sudo apt-get update
          sudo apt-get install -y binfmt-support qemu-user-static jq
          mkdir -p ~/.docker/cli-plugins
          BUILDX_URL=$(curl https://api.github.com/repos/docker/buildx/releases/latest | jq -r .assets[].browser_download_url | grep amd64 | grep linux)
          wget $BUILDX_URL -O ~/.docker/cli-plugins/docker-buildx
          chmod +x ~/.docker/cli-plugins/docker-buildx
          docker buildx create --name xbuilder
          docker buildx use xbuilder
          docker buildx inspect --bootstrap
      - name: Log in to registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Log in to GHCR registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --tag quay.io/mect/pg-backup-s3:$GITHUB_SHA --push --platform "linux/amd64,linux/arm64,linux/arm"
      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --tag ghcr.io/mect/pg-backup-s3:$GITHUB_SHA --push --platform "linux/amd64,linux/arm64,linux/arm"
