name: Docker Image Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm32v7, arm64v8]
    steps:
      - uses: actions/checkout@v1
      - name: Get qemu-user-static
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - name: Configure Docker
        run: |
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          docker run --rm --privileged multiarch/qemu-user-static:register
      - name: Build the Docker image
        run: |
          if [[ "$ARCH" == "amd64" ]]; then export GOARCH="amd64"; fi
          if [[ "$ARCH" == "arm32v7" ]]; then export GOARCH="arm"; fi
          if [[ "$ARCH" == "arm64v8" ]]; then export GOARCH="arm64"; fi
          docker build . --build-arg="ARCH=$ARCH" --build-arg="GOARCH=$GOARCH" --file Dockerfile --tag quay.io/mect/pg-backup-s3:${{ matrix.arch }}-$GITHUB_SHA
        env:
          ARCH: ${{ matrix.arch }}
          DOCKER_CLI_EXPERIMENTAL: enabled
      - name: Log in to registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push image
        run: docker push quay.io/mect/pg-backup-s3:${{ matrix.arch }}-$GITHUB_SHA
  publish-manifest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Configure Docker
        run: |
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          docker run --rm --privileged multiarch/qemu-user-static:register
      - name: Log in to registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Create Manifest
        run: |
          docker manifest create $DOCKER_PREFIX:$GITHUB_SHA $DOCKER_PREFIX:amd64-$GITHUB_SHA $DOCKER_PREFIX:arm32v7-$GITHUB_SHA $DOCKER_PREFIX:arm64v8-$GITHUB_SHA
          docker manifest annotate $DOCKER_PREFIX:$GITHUB_SHA $DOCKER_PREFIX:amd64-$GITHUB_SHA --arch amd64
          docker manifest annotate $DOCKER_PREFIX:$GITHUB_SHA $DOCKER_PREFIX:arm32v7-$GITHUB_SHA --arch arm --variant v7
          docker manifest annotate $DOCKER_PREFIX:$GITHUB_SHA $DOCKER_PREFIX:arm64v8-$GITHUB_SHA --arch arm64 --variant armv8
          docker manifest push $DOCKER_PREFIX:$GITHUB_SHA
        env:
          DOCKER_PREFIX: quay.io/mect/pg-backup-s3
          DOCKER_CLI_EXPERIMENTAL: enabled
